spring.application.name=account-service
server.port=8081


spring.datasource.url=jdbc:postgresql://localhost:5432/bank_account
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
jwt.secret=${JWT_SECRET}

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka